<?php

namespace AppBundle\Repository;

/**
 * DmonteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DmonteurRepository extends \Doctrine\ORM\EntityRepository
{
}
