<?php

namespace AppBundle\Repository;

/**
 * NlbeleverlingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NlbeleveringRepository extends \Doctrine\ORM\EntityRepository
{
}
