<?php

namespace AppBundle\Repository;

/**
 * VoorraadlijstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoorraadlijstRepository extends \Doctrine\ORM\EntityRepository
{
}
